version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1048576
      POSTGRES_DB: nest
      POSTGRES_PORT: 5432
